=== RMLio/algemaploom-rs/schema/mapping_plan_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema for the mapping plan generated from the algemaploom-rs translator",
    "type": "object",
    "properties": {
        "nodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "operator": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": {
                                    "enum": [
                                        "SourceOp",
                                        "ProjectionOp",
                                        "RenameOp",
                                        "ExtendOp",
                                        "SerializeOp",
                                        "TargetOp",
                                        "Fragmenter",
                                        "Join",
                                        "Union",
                                        "LeftJoin"
                                    ],
                                    "$comment": "Types of the operator"
                                }
                            },
                            "config": {
                                "type": "object",
                                "properties": {
                                    "path": {
                                        "type": "string",
                                        "$comment": "URI path of the input data source"
                                    },
                                    "source_type": {
                                        "type": {
                                            "enum": [
                                                "File",
                                                "Kafka",
                                                "WebSocket"
                                            ]
                                        },
                                        "$comment": "The type of input data source"
                                    },
                                    "root_iterator": {
                                        "type": "object",
                                        "properties": {
                                            "reference": {
                                                "type": "string",
                                                "$comment": "Query string such as JSONPath query or XPath query. Can be empty for formats such as CSV files since they do not have queries. "
                                            },
                                            "reference_formulation": {
                                                "$ref": "#/$defs/reference_formulation"
                                            },
                                            "fields": {
                                                "$ref": "#/$defs/fields"
                                            }
                                        },
                                        "required": [
                                            "reference_formulation",
                                            "fields"
                                        ]
                                    },
                                    "projection_attributes": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "?variable": {
                                        "$ref": "#/$defs/extend_expression",
                                        "$comment": "An extend expression"
                                    },
                                    "from": {
                                        "type": "string",
                                        "$comment": "Incoming fragment label"
                                    },
                                    "to": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        },
                                        "$comment": "Outgoing fragment labels"
                                    },
                                    "template": {
                                        "type": "string",
                                        "$comment": "The template string used by the serializer to replace the variables in the template with the values from the mapping tuples;"
                                    },
                                    "format": {
                                        "type": "string",
                                        "$comment": "Data format of the serializer"
                                    },
                                    "target_type": {
                                        "type": "string"
                                    },
                                    "data_format": {
                                        "type": "string"
                                    }
                                },
                                "required": []
                            }
                        },
                        "required": [
                            "type",
                            "config"
                        ]
                    }
                },
                "required": [
                    "id",
                    "operator"
                ]
            }
        },
        "node_holes": {
            "type": "array",
            "items": {}
        },
        "edge_property": {
            "type": "string"
        },
        "edges": {
            "type": "array",
            "items": {
                "type": "array",
                "items": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "number"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "fragment": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "fragment"
                        ]
                    }
                ],
                "additionalItems": false
            }
        }
    },
    "required": [
        "nodes",
        "node_holes",
        "edge_property",
        "edges"
    ],
    "$defs": {
        "reference_formulation": {
            "type": {
                "enum": [
                    "CSVRows",
                    "JSONPath",
                    "XPath"
                ]
            }
        },
        "fields": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "alias": {
                        "type": "string"
                    },
                    "reference": {
                        "type": "string"
                    },
                    "reference_formulation": {
                        "$ref": "#/$defs/reference_formulation"
                    },
                    "inner_fields": {
                        "$ref": "#/$defs/fields"
                    }
                },
                "required": [
                    "alias",
                    "reference",
                    "reference_formulation",
                    "inner_fields"
                ]
            }
        },
        "inner_function": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "config": {
                    "type": "object"
                },
                "inner_function": {
                    "$ref": "#/$defs/inner_function"
                }
            },
            "required": [
                "type",
                "inner_function"
            ]
        },
        "extend_expression": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "Literal",
                        "BlankNode",
                        "IRI"
                    ]
                },
                "inner_function": {
                    "$ref": "#/$defs/inner_function"
                },
                "base_iri": {
                    "type": "string"
                },
                "dtype_function": {
                    "type": "object"
                },
                "lang_function": {
                    "type": "object"
                }
            },
            "required": [
                "type",
                "inner_function"
            ]
        }
    }
}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0006a-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"student.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"<http://example.com/BadStudent> <http://example.com/description> \"Bad Student\" <http://example.com/graph/student> .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-lv-tests/RMLLVTC0001a/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"people.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.people[*]","reference_formulation":"JSONPath","fields":[{"alias":"name","absolute_path":"name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"name"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/person/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"name"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.org/hasName> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-lv-tests/RMLLVTC0001d/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"people.json"},"source_type":"File","root_iterator":{"reference":"$.people[*]","reference_formulation":"JSONPath","fields":[{"alias":"name","absolute_path":"name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"lastName","absolute_path":"lastName","reference":"$.lastName","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Reference","value":"name"}},"separator":"","right_value":{"type":"Constant","value":" "}},"separator":"","right_value":{"type":"Reference","value":"lastName"}},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/person/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"name"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.org/hasFullName> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0023a-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"student.json"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[{"alias":"Name","absolute_path":"Name","reference":"Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"","absolute_path":"","reference":"","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"Name"}}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":""}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLSTC0001b/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"encoding":"http://w3id.org/rml/UTF-16","access":{"root":"http://w3id.org/rml/MappingDirectory","path":"Friends-UTF16.json"},"source_type":"File","root_iterator":{"reference":"$[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.age","absolute_path":"$.age","reference":"$.age","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.name","absolute_path":"$.name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.id","absolute_path":"$.id","reference":"$.id","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.age"},"dtype_function":null,"langtype_function":null},"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.name"},"dtype_function":null,"langtype_function":null}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .\n?sm_0 <http://xmlns.com/foaf/0.1/age> ?pom_0_1_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-lv-tests/RMLLVTC0002a/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"people.json"},"source_type":"File","root_iterator":{"reference":"$.people[*]","reference_formulation":"JSONPath","fields":[{"alias":"name","absolute_path":"name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"item","absolute_path":"item","reference":null,"constant":null,"iterator":"$.items[*]","reference_formulation":"JSONPath","inner_fields":[{"alias":"type","absolute_path":"item.type","reference":"$.type","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/person/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"name"}}}},"pom_0_0_om_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/person/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"name"}}},"separator":"","right_value":{"type":"Constant","value":"/item/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"item.type"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.org/hasItem> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0026d-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"persons.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.persons[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.amount","absolute_path":"$.amount","reference":"$.amount","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.fname","absolute_path":"$.fname","reference":"$.fname","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.lname","absolute_path":"$.lname","reference":"$.lname","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.amount","absolute_path":"$.amount","reference":"$.amount","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_1_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.amount"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"http://example2.com/","inner_function":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.fname"}}}},"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.amount"},"dtype_function":null,"langtype_function":null},"sm_1":{"type":"Iri","base_iri":"http://example2.com/","inner_function":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.lname"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/amount> ?pom_0_0_om_0 .\n?sm_1 <http://example.com/amount> ?pom_1_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0022c-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"data.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.FOO","absolute_path":"$.FOO","reference":"$.FOO","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.BAR","absolute_path":"$.BAR","reference":"$.BAR","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.FOO"},"dtype_function":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"datatype#"}},"separator":"","right_value":{"type":"Reference","value":"$.BAR"}}},"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.FOO"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/x> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}
