=== RMLio/algemaploom-rs/schema/mapping_plan_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema for the mapping plan generated from the algemaploom-rs translator",
    "type": "object",
    "properties": {
        "nodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "operator": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": {
                                    "enum": [
                                        "SourceOp",
                                        "ProjectionOp",
                                        "RenameOp",
                                        "ExtendOp",
                                        "SerializeOp",
                                        "TargetOp",
                                        "Fragmenter",
                                        "Join",
                                        "Union",
                                        "LeftJoin"
                                    ],
                                    "$comment": "Types of the operator"
                                }
                            },
                            "config": {
                                "type": "object",
                                "properties": {
                                    "path": {
                                        "type": "string",
                                        "$comment": "URI path of the input data source"
                                    },
                                    "source_type": {
                                        "type": {
                                            "enum": [
                                                "File",
                                                "Kafka",
                                                "WebSocket"
                                            ]
                                        },
                                        "$comment": "The type of input data source"
                                    },
                                    "root_iterator": {
                                        "type": "object",
                                        "properties": {
                                            "reference": {
                                                "type": "string",
                                                "$comment": "Query string such as JSONPath query or XPath query. Can be empty for formats such as CSV files since they do not have queries. "
                                            },
                                            "reference_formulation": {
                                                "$ref": "#/$defs/reference_formulation"
                                            },
                                            "fields": {
                                                "$ref": "#/$defs/fields"
                                            }
                                        },
                                        "required": [
                                            "reference_formulation",
                                            "fields"
                                        ]
                                    },
                                    "projection_attributes": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "?variable": {
                                        "$ref": "#/$defs/extend_expression",
                                        "$comment": "An extend expression"
                                    },
                                    "from": {
                                        "type": "string",
                                        "$comment": "Incoming fragment label"
                                    },
                                    "to": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        },
                                        "$comment": "Outgoing fragment labels"
                                    },
                                    "template": {
                                        "type": "string",
                                        "$comment": "The template string used by the serializer to replace the variables in the template with the values from the mapping tuples;"
                                    },
                                    "format": {
                                        "type": "string",
                                        "$comment": "Data format of the serializer"
                                    },
                                    "target_type": {
                                        "type": "string"
                                    },
                                    "data_format": {
                                        "type": "string"
                                    }
                                },
                                "required": []
                            }
                        },
                        "required": [
                            "type",
                            "config"
                        ]
                    }
                },
                "required": [
                    "id",
                    "operator"
                ]
            }
        },
        "node_holes": {
            "type": "array",
            "items": {}
        },
        "edge_property": {
            "type": "string"
        },
        "edges": {
            "type": "array",
            "items": {
                "type": "array",
                "items": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "number"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "fragment": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "fragment"
                        ]
                    }
                ],
                "additionalItems": false
            }
        }
    },
    "required": [
        "nodes",
        "node_holes",
        "edge_property",
        "edges"
    ],
    "$defs": {
        "reference_formulation": {
            "type": {
                "enum": [
                    "CSVRows",
                    "JSONPath",
                    "XPath"
                ]
            }
        },
        "fields": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "alias": {
                        "type": "string"
                    },
                    "reference": {
                        "type": "string"
                    },
                    "reference_formulation": {
                        "$ref": "#/$defs/reference_formulation"
                    },
                    "inner_fields": {
                        "$ref": "#/$defs/fields"
                    }
                },
                "required": [
                    "alias",
                    "reference",
                    "reference_formulation",
                    "inner_fields"
                ]
            }
        },
        "inner_function": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "config": {
                    "type": "object"
                },
                "inner_function": {
                    "$ref": "#/$defs/inner_function"
                }
            },
            "required": [
                "type",
                "inner_function"
            ]
        },
        "extend_expression": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "Literal",
                        "BlankNode",
                        "IRI"
                    ]
                },
                "inner_function": {
                    "$ref": "#/$defs/inner_function"
                },
                "base_iri": {
                    "type": "string"
                },
                "dtype_function": {
                    "type": "object"
                },
                "lang_function": {
                    "type": "object"
                }
            },
            "required": [
                "type",
                "inner_function"
            ]
        }
    }
}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0007e-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"student.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.Name","absolute_path":"$.Name","reference":"$.Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.ID","absolute_path":"$.ID","reference":"$.ID","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.ID"},"dtype_function":null,"langtype_function":null},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.Name"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/Student/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}},"separator":"","right_value":{"type":"Constant","value":"/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.Name"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/id> ?pom_0_0_om_0 <http://example.com/PersonGraph> .\n?sm_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> <http://example.com/PersonGraph> .\n?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_1_om_0 <http://example.com/PersonGraph> .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0015a-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"country_es.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.countries[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.Name","absolute_path":"$.Name","reference":"$.Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.Code","absolute_path":"$.Code","reference":"$.Code","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"Source_1","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"country_en.json"},"source_type":"File","root_iterator":{"reference":"$.countries[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.Code","absolute_path":"$.Code","reference":"$.Code","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.Name","absolute_path":"$.Name","reference":"$.Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_2","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.Name"},"dtype_function":null,"langtype_function":{"type":"Constant","value":"en"}},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.Code"}}}}}}},{"id":"Serialize_3","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://www.w3.org/2000/01/rdf-schema#label> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_4","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}},{"id":"ExtendOperator_5","operator":{"type":"ExtendOp","config":{"sm_1":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.Code"}}}},"pom_1_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.Name"},"dtype_function":null,"langtype_function":{"type":"Constant","value":"es"}}}}},{"id":"Serialize_6","operator":{"type":"SerializerOp","config":{"template":"?sm_1 <http://www.w3.org/2000/01/rdf-schema#label> ?pom_1_0_om_0 .","format":"NQuads"}}},{"id":"Sink_7","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}],[3,4,{"fragment":"default","direction":"Center"}],[0,5,{"fragment":"default","direction":"Center"}],[5,6,{"fragment":"default","direction":"Center"}],[6,7,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLTTC0002i/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"Friends.json"},"source_type":"File","root_iterator":{"reference":"$[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.id","absolute_path":"$.id","reference":"$.id","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.name","absolute_path":"$.name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.age","absolute_path":"$.age","reference":"$.age","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/ .","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}},"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.name"},"dtype_function":null,"langtype_function":{"type":"Constant","value":"en"}},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.age"},"dtype_function":null,"langtype_function":null}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/age> ?pom_0_1_om_0 <http://example.org/PeopleGraph> .\n?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 <http://example.org/PeopleGraph> .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-cc-tests/RMLTC-CC-0006-IT4/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"data.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.*","reference_formulation":"JSONPath","fields":[{"alias":"$.id","absolute_path":"$.id","reference":"$.id","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"e/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}},"pom_0_0_om_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"c/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/ns#with> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0007b-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"student.json"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.ID","absolute_path":"$.ID","reference":"$.ID","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.FirstName","absolute_path":"$.FirstName","reference":"$.FirstName","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/Student/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}},"separator":"","right_value":{"type":"Constant","value":"/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.FirstName"}}}},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.FirstName"},"dtype_function":null,"langtype_function":null}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> <http://example.com/PersonGraph> .\n?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_1_om_0 <http://example.com/PersonGraph> .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0030e-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"student.json"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.ID","absolute_path":"$.ID","reference":"$.ID","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.Name","absolute_path":"$.Name","reference":"$.Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"Source_1","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"sport.json"},"source_type":"File","root_iterator":{"reference":"$.sports[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.Name","absolute_path":"$.Name","reference":"$.Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.ID","absolute_path":"$.ID","reference":"$.ID","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"RenameOp_2","operator":{"type":"RenameOp","config":{"alias":"join_alias"}}},{"id":"Join_3","operator":{"type":"JoinOp","config":{"left_right_attr_pairs":[],"join_type":"InnerJoin","predicate_type":"Equal"}}},{"id":"ExtendOp_4","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/resource/student_"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}}},"sm_1_obj":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/resource/sport_"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"join_alias.$.ID"}}}}}}},{"id":"Serialize_5","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/ontology/practises> ?sm_1_obj .","format":"NQuads"}}},{"id":"Sink_6","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}},{"id":"ExtendOperator_7","operator":{"type":"ExtendOp","config":{"sm_1":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/resource/sport_"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}}},"pom_1_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.Name"},"dtype_function":null,"langtype_function":null}}}},{"id":"Serialize_8","operator":{"type":"SerializerOp","config":{"template":"?sm_1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ontology/Sport> .\n?sm_1 <http://www.w3.org/2000/01/rdf-schema#label> ?pom_1_0_om_0 .","format":"NQuads"}}},{"id":"Sink_9","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}},{"id":"ExtendOperator_10","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/resource/student_"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}}},"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.Name"},"dtype_function":null,"langtype_function":null}}}},{"id":"Serialize_11","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.com/ontology/Student> .\n?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_12","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[1,2,{"fragment":"default","direction":"Center"}],[0,3,{"fragment":"join_alias","direction":"Left"}],[2,3,{"fragment":"join_alias","direction":"Right"}],[3,4,{"fragment":"default","direction":"Center"}],[4,5,{"fragment":"default","direction":"Center"}],[5,6,{"fragment":"default","direction":"Center"}],[1,7,{"fragment":"default","direction":"Center"}],[7,8,{"fragment":"default","direction":"Center"}],[8,9,{"fragment":"default","direction":"Center"}],[0,10,{"fragment":"default","direction":"Center"}],[10,11,{"fragment":"default","direction":"Center"}],[11,12,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-cc-tests/RMLTC-CC-0010-Listb/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"data.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.*","reference_formulation":"JSONPath","fields":[{"alias":"$.graph","absolute_path":"$.graph","reference":"$.graph","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.id","absolute_path":"$.id","reference":"$.id","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_gm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"g/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.graph"}}}},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"e/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}},"pom_0_0_om_0":{"type":"BlankNode","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"l/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/ns#with> ?pom_0_0_om_0 ?pom_0_0_gm_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0027c-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"student.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.Name","absolute_path":"$.Name","reference":"$.Name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/Person/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.Name"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://xmlns.com/foaf/0.1/Person> .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}
