=== RMLio/algemaploom-rs/schema/mapping_plan_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema for the mapping plan generated from the algemaploom-rs translator",
    "type": "object",
    "properties": {
        "nodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "operator": {
                        "type": "object",
                        "properties": {
                            "type": {
                                "type": {
                                    "enum": [
                                        "SourceOp",
                                        "ProjectionOp",
                                        "RenameOp",
                                        "ExtendOp",
                                        "SerializeOp",
                                        "TargetOp",
                                        "Fragmenter",
                                        "Join",
                                        "Union",
                                        "LeftJoin"
                                    ],
                                    "$comment": "Types of the operator"
                                }
                            },
                            "config": {
                                "type": "object",
                                "properties": {
                                    "path": {
                                        "type": "string",
                                        "$comment": "URI path of the input data source"
                                    },
                                    "source_type": {
                                        "type": {
                                            "enum": [
                                                "File",
                                                "Kafka",
                                                "WebSocket"
                                            ]
                                        },
                                        "$comment": "The type of input data source"
                                    },
                                    "root_iterator": {
                                        "type": "object",
                                        "properties": {
                                            "reference": {
                                                "type": "string",
                                                "$comment": "Query string such as JSONPath query or XPath query. Can be empty for formats such as CSV files since they do not have queries. "
                                            },
                                            "reference_formulation": {
                                                "$ref": "#/$defs/reference_formulation"
                                            },
                                            "fields": {
                                                "$ref": "#/$defs/fields"
                                            }
                                        },
                                        "required": [
                                            "reference_formulation",
                                            "fields"
                                        ]
                                    },
                                    "projection_attributes": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "?variable": {
                                        "$ref": "#/$defs/extend_expression",
                                        "$comment": "An extend expression"
                                    },
                                    "from": {
                                        "type": "string",
                                        "$comment": "Incoming fragment label"
                                    },
                                    "to": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        },
                                        "$comment": "Outgoing fragment labels"
                                    },
                                    "template": {
                                        "type": "string",
                                        "$comment": "The template string used by the serializer to replace the variables in the template with the values from the mapping tuples;"
                                    },
                                    "format": {
                                        "type": "string",
                                        "$comment": "Data format of the serializer"
                                    },
                                    "target_type": {
                                        "type": "string"
                                    },
                                    "data_format": {
                                        "type": "string"
                                    }
                                },
                                "required": []
                            }
                        },
                        "required": [
                            "type",
                            "config"
                        ]
                    }
                },
                "required": [
                    "id",
                    "operator"
                ]
            }
        },
        "node_holes": {
            "type": "array",
            "items": {}
        },
        "edge_property": {
            "type": "string"
        },
        "edges": {
            "type": "array",
            "items": {
                "type": "array",
                "items": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "number"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "fragment": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "fragment"
                        ]
                    }
                ],
                "additionalItems": false
            }
        }
    },
    "required": [
        "nodes",
        "node_holes",
        "edge_property",
        "edges"
    ],
    "$defs": {
        "reference_formulation": {
            "type": {
                "enum": [
                    "CSVRows",
                    "JSONPath",
                    "XPath"
                ]
            }
        },
        "fields": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "alias": {
                        "type": "string"
                    },
                    "reference": {
                        "type": "string"
                    },
                    "reference_formulation": {
                        "$ref": "#/$defs/reference_formulation"
                    },
                    "inner_fields": {
                        "$ref": "#/$defs/fields"
                    }
                },
                "required": [
                    "alias",
                    "reference",
                    "reference_formulation",
                    "inner_fields"
                ]
            }
        },
        "inner_function": {
            "type": "object",
            "properties": {
                "type": {
                    "type": "string"
                },
                "value": {
                    "type": "string"
                },
                "config": {
                    "type": "object"
                },
                "inner_function": {
                    "$ref": "#/$defs/inner_function"
                }
            },
            "required": [
                "type",
                "inner_function"
            ]
        },
        "extend_expression": {
            "type": "object",
            "properties": {
                "type": {
                    "enum": [
                        "Literal",
                        "BlankNode",
                        "IRI"
                    ]
                },
                "inner_function": {
                    "$ref": "#/$defs/inner_function"
                },
                "base_iri": {
                    "type": "string"
                },
                "dtype_function": {
                    "type": "object"
                },
                "lang_function": {
                    "type": "object"
                }
            },
            "required": [
                "type",
                "inner_function"
            ]
        }
    }
}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLSTC0012e/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"companies.xml","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"/companies/company/departments/department/employees/employee","reference_formulation":{"XMLPath":{"namespaces":[]}},"fields":[{"alias":"name","absolute_path":"name","reference":"name","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[]}},"inner_fields":[]},{"alias":"skills/skill","absolute_path":"skills/skill","reference":"skills/skill","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[]}},"inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"skills/skill"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"name"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://example.com/skill> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLTTC0007a/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"path":"Friends.json","root":"http://w3id.org/rml/MappingDirectory"},"source_type":"File","root_iterator":{"reference":"$[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.id","absolute_path":"$.id","reference":"$.id","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.name","absolute_path":"$.name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.age","absolute_path":"$.age","reference":"$.age","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.name"},"dtype_function":null,"langtype_function":null},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.age"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/age> ?pom_0_1_om_0 .\n?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLSTC0011d/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"companies.json"},"source_type":"File","root_iterator":{"reference":"$.companies[*].departments[*]","reference_formulation":"JSONPath","fields":[{"alias":"name","absolute_path":"name","reference":"name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.manager.name","absolute_path":"$.manager.name","reference":"$.manager.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"name"}}}},"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.manager.name"},"dtype_function":null,"langtype_function":null}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLTTC0002q/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"Friends.json"},"source_type":"File","root_iterator":{"reference":"$[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.id","absolute_path":"$.id","reference":"$.id","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.age","absolute_path":"$.age","reference":"$.age","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.name","absolute_path":"$.name","reference":"$.name","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.id"}}}},"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.name"},"dtype_function":null,"langtype_function":null},"pom_0_2_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.age"},"dtype_function":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Constant","value":"http://www.w3.org/2001/XMLSchema#double"}},"langtype_function":null},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.age"},"dtype_function":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Constant","value":"http://www.w3.org/2001/XMLSchema#integer"}},"langtype_function":null}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .\n?sm_0 <http://xmlns.com/foaf/0.1/age> ?pom_0_1_om_0 .\n?sm_0 <http://xmlns.com/foaf/0.1/age> ?pom_0_2_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0003c-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"student.json"},"source_type":"File","root_iterator":{"reference":"$.students[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.LastName","absolute_path":"$.LastName","reference":"$.LastName","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.ID","absolute_path":"$.ID","reference":"$.ID","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.FirstName","absolute_path":"$.FirstName","reference":"$.FirstName","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Reference","value":"$.FirstName"}},"separator":"","right_value":{"type":"Constant","value":" "}},"separator":"","right_value":{"type":"Reference","value":"$.LastName"}},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/Student"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-core-tests/RMLTC0031c-JSON/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"data.json"},"source_type":"File","root_iterator":{"reference":"$[*]","reference_formulation":"JSONPath","fields":[{"alias":"$.region","absolute_path":"$.region","reference":"$.region","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.language","absolute_path":"$.language","reference":"$.language","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.ID","absolute_path":"$.ID","reference":"$.ID","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]},{"alias":"$.label","absolute_path":"$.label","reference":"$.label","constant":null,"iterator":null,"reference_formulation":"JSONPath","inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"$.label"},"dtype_function":null,"langtype_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Reference","value":"$.language"}},"separator":"","right_value":{"type":"Constant","value":"-"}},"separator":"","right_value":{"type":"Reference","value":"$.region"}}},"sm_0":{"type":"Iri","base_iri":"","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.com/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"$.ID"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://www.w3.org/2000/01/rdf-schema#label> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLSTC0012a/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"companies.xml"},"source_type":"File","root_iterator":{"reference":"/companies/company","reference_formulation":{"XMLPath":{"namespaces":[]}},"fields":[{"alias":"@id","absolute_path":"@id","reference":"@id","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[]}},"inner_fields":[]},{"alias":"name","absolute_path":"name","reference":"name","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[]}},"inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"name"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"@id"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}

=== RMLio/algemaploom-rs/crates/translator_new_rml/resources/test/rml-io-tests/RMLSTC0007d/mapping.json
{"nodes":[{"id":"Source_0","operator":{"type":"SourceOp","config":{"access":{"root":"http://w3id.org/rml/MappingDirectory","path":"Friends.xml"},"source_type":"File","root_iterator":{"reference":"//Friends/ex:Character","reference_formulation":{"XMLPath":{"namespaces":[{"prefix":"ex","url":"http://example.org"}]}},"fields":[{"alias":"ex:age/text()","absolute_path":"ex:age/text()","reference":"ex:age/text()","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[{"prefix":"ex","url":"http://example.org"}]}},"inner_fields":[]},{"alias":"@id","absolute_path":"@id","reference":"@id","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[{"prefix":"ex","url":"http://example.org"}]}},"inner_fields":[]},{"alias":"ex:name/text()","absolute_path":"ex:name/text()","reference":"ex:name/text()","constant":null,"iterator":null,"reference_formulation":{"XMLPath":{"namespaces":[{"prefix":"ex","url":"http://example.org"}]}},"inner_fields":[]}],"alias":null}}}},{"id":"ExtendOperator_1","operator":{"type":"ExtendOp","config":{"pom_0_0_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"ex:name/text()"},"dtype_function":null,"langtype_function":null},"pom_0_1_om_0":{"type":"Literal","inner_function":{"type":"Reference","value":"ex:age/text()"},"dtype_function":null,"langtype_function":null},"sm_0":{"type":"Iri","base_iri":"http://example.com/rules/","inner_function":{"type":"Concatenate","left_value":{"type":"Concatenate","left_value":{"type":"Nop"},"separator":"","right_value":{"type":"Constant","value":"http://example.org/"}},"separator":"","right_value":{"type":"UriEncode","inner_function":{"type":"Reference","value":"@id"}}}}}}},{"id":"Serialize_2","operator":{"type":"SerializerOp","config":{"template":"?sm_0 <http://xmlns.com/foaf/0.1/name> ?pom_0_0_om_0 .\n?sm_0 <http://xmlns.com/foaf/0.1/age> ?pom_0_1_om_0 .","format":"NQuads"}}},{"id":"Sink_3","operator":{"type":"TargetOp","config":{"target_type":"StdOut","data_format":"NQuads"}}}],"node_holes":[],"edge_property":"directed","edges":[[0,1,{"fragment":"default","direction":"Center"}],[1,2,{"fragment":"default","direction":"Center"}],[2,3,{"fragment":"default","direction":"Center"}]]}
